# Generated by Django 4.1.1 on 2022-09-23 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'SUPER_ADMIN'), ('ADMIN', 'ADMIN'), ('USER', 'USER')], max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vehicle_description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vehicle_model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vehicle_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='vehicletypemodel',
            name='vehicle_type',
            field=models.CharField(max_length=25),
        ),
    ]
